### ISSUE TITLE
QC and analysis of uncertainty in the structural/geological framework

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface#69]
Epic for dashboard functionality needed to analyze structural uncertainty results.

Relates to #63

@jcrivenaes
@perolavsvendsen
@daniel-sollien

Available functionality should consist of several map views, as well as a cross-section view along a well or a digitized polyline. Additionally a chart view showing histogram, scatterplot and box plot could be utilized to show mismatch between e.g. surface depths and well data.

Different surface types and stratigraphical elements should be selectable by the user, and it should be possible to visualize both single realizations, statistical surfaces and calculated difference maps between different types/stratigraphical elements.

Well information should include HUM results such as mismatch, outliers and deleted data.

### Data input and processing

- [ ] On-the-fly calculation of statistical surfaces from an ensemble 

- [ ] On-the-fly calculation of difference surfaces from a realization or from statistical surfaces 

- [ ] Define data format for well picks with HUM attributes

- [ ] Define input configuration to list surface types and stratigraphical column

- [ ] Calculate surface intersections from a digitized polyline / well path

### Map visualization

- [ ] Visualize a single surface realization

- [ ] Visualize a statistical surface from an ensemble

- [ ] Visualize difference surfaces (isochores) per realization or from statistical surfaces

- [ ] Visualize well paths 

- [ ] Visualize well pick markers

### Intersection view

- [ ] Visualize multiple realizations

- [ ] Visualize statistical surfaces with color fill between e.g. min/max or p10/p90

- [ ] Visualize well paths with zonelog

- [ ] Visualize well pick markers

### Chart view

- [ ] Statistical information for a given surface type / stratigraphical element, e.g. variation in depth within an area or deviation from well picks.

- [ ] Zone log mismatch

### Interactivity

- [ ] Select different surface types and stratigraphy

- [ ] Select well

- [ ] Select realizations / iterations

- [ ] Digitize polyline in map view 

- [ ] Select statistical calculation

**Comment by anders-kiaer** [comment]
Closed as of today.
