### ISSUE TITLE
Restructure `ReservoirSimulationTimeSeries`

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#698]
The current plugin has "been with us" since the start, and has been extended by different people during the project period. Time to consolidate/restructure/improve the code.

Related issues:
- #677
- #630
- #502
- #488 
- #402
- #335
- #321
- #214

Functionality for calculating new custom vectors, delta between ensembles etc. should be in separate modules (as other plugins will need the same calculation options).

**Comment by anders-kiaer** [comment]
Quick summary from meeting between @asnyv, @jorgenherje and myself going through the linked issues above:

* Create a common utility to create fan chart input to plotly `dcc.Graph`.
   * Make mean independent of the shades (but keep in same legend group).
* Try to fetch user selected date range in plotly graph and use it when changing to new vector. 
* Create UI (and later support it in the plugin) for showing multiple ensembles (with varying A and B).
   * @jorgenherje to make some UI sketches before implementing. 
* Support user defined vector annotations as input to plugin.
   * E.g. user defined descriptions of user defined UDQ.
   * E.g. user defined annotations (`[{vector, datetime, label}]`).

* Stacking possibility (i.e. show time series in same plot)
   * across ensembles enforces same vector
   * if multiple vectors enforces same ensemble.
* Statistics + individual realizations in same plot.
* Secondary axis (and/or third axis?) 
  * Automatically decide if same axis or different axis based on "same unit and not order of magnitude difference in max/min).

**Related factory responsibility (@sigurdp):**
* Support metadata through `.csv` (in addition to `.arrow` and from `.UNSMRY`). We can define how that metadata should come together with the `.csv`.

**Comment by jorgenherje** [comment]
Above mentioned summary as checklist (for @jorgenherje):

- [ ] Create a common utility to create fan chart input to plotly `dcc.Graph`.
   * Make mean independent of the shades (but keep in same legend group).
- [ ] Try to fetch user selected date range in plotly graph and use it when changing to new vector. 
- [ ] Create UI (and later support it in the plugin) for showing multiple ensembles (with varying A and B).
   * @jorgenherje to make some UI sketches before implementing. 
- [ ] Support user defined vector annotations as input to plugin.
   * E.g. user defined descriptions of user defined UDQ.
   * E.g. user defined annotations (`[{vector, datetime, label}]`).

- [ ] Stacking possibility (i.e. show time series in same plot)
   * across ensembles enforces same vector
   * if multiple vectors enforces same ensemble.
- [ ] Statistics + individual realizations in same plot.
- [ ] Secondary axis (and/or third axis?) 
  * Automatically decide if same axis or different axis based on "same unit and not order of magnitude difference in max/min).

**Related factory responsibility (@sigurdp):**
* Support metadata through `.csv` (in addition to `.arrow` and from `.UNSMRY`). We can define how that metadata should come together with the `.csv`.

**Comment by jorgenherje** [comment]
Refactoring done.

Two bullet points has gotten new issues:
* https://github.com/equinor/webviz-subsurface/issues/954
* https://github.com/equinor/webviz-subsurface/issues/942
