### ISSUE TITLE
Move away from `.UNSMRY` to `.arrow` provider

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#858]
- [x] `ParameterAnalysis` @tnatt 
- [x] `GroupTree` @lindjoha - #902 
- [x] `PropertyStatistics`
- [x] `BhpQc` @rnyb 
- [x] `ParameterResponseCorrelation` @lindjoha 
- [ ] `ReservoirSimulationTimeSeriesOneByOne` @tnatt and @lindjoha #1217 
- [ ] `ReservoirSimulationTimeseriesRegional` @asnyv 
- [ ] `ParameterParallelCoordinates` @anders-kiaer 
- [ ] `HistoryMatch` - ping ERT-team if they can dump data as input to us (@anders-kiaer)

Don't think these currently support directly from UNSMRY, but supports from csv, and should ideally have summary support. In that way they can be used with the same providers as the others if defined with the same data, avoiding unnecessary overhead
- [ ] `LinePlotter` (currently only supports csv, but common user request to have special support for summary data)
- [ ] `TornadoPlotterFMU`  (Similar to  supports csv, but common user request to have special support for summary data)
